<FirstScreen>:
    GridLayout:
        cols:1
        padding: 10
        spacing: 10
        Image:
            id: image
            size_hint_y: 0.8
        TextInput:
            id: word
            hint_text: "Enter word"
            size_hint_y: 0.1
        Button:
            text: "Search Image"
            size_hint_y: 0.1
            on_press: root.set_image()


<RootWidget>:
    FirstScreen:
        id: first_screen
        name: 'first_screen'

